/**
 * Review body rendering.
 *
 * Everything a human reads on the pull request is built here. Three properties
 * govern the output:
 *
 * 1. **No markdown injection from untrusted content.** The diff is untrusted and
 *    the model's explanation is untrusted. Both end up in a comment rendered by
 *    GitHub's markdown engine, where a crafted explanation could close a
 *    details block, fake a code fence, or impersonate a bot. So every
 *    untrusted string is either fenced, escaped, or stripped of the characters
 *    that carry structure.
 *
 * 2. **The source quote is never rendered as markdown.** It is the highest-risk
 *    string in the payload: it came from a file, it is arbitrary text, and it
 *    can contain anything. It goes in a fenced block whose fence is chosen
 *    longer than the content, so a ``` inside the quote cannot escape.
 *
 * 3. **The review says what it is.** Advisory, model-generated, and able to be
 *    wrong. A reader who cannot tell an AI finding from a human one cannot
 *    calibrate their response to it, which is how advisory tools get treated as
 *    authoritative.
 */

import type { AnchoredFinding, Severity } from "../types.js";

/** Fence long enough to wrap any quote the schema accepts. */
const MAX_QUOTE_LENGTH = 1_200;

/** Lines of a quote shown before truncation. */
const MAX_QUOTE_LINES = 12;

export const SEVERITY_LABELS: Readonly<Record<Severity, string>> = {
  critical: "Critical",
  warning: "Warning",
  info: "Note",
};

/** A fence strictly longer than anything in the content it wraps. */
export function safeFence(content: string): string {
  let longest = 0;
  for (const match of content.matchAll(/`+/g)) {
    longest = Math.max(longest, match[0].length);
  }
  return "`".repeat(Math.max(3, longest + 1));
}

/**
 * Neutralise markdown structure in untrusted prose.
 *
 * Inline code spans and emphasis are the two constructs that let untrusted text
 * escape its intended rendering. Both are escaped; the sentence still reads,
 * and it can no longer carry structure.
 *
 * Deliberately not escaped: pipes outside a table, and newlines, because the
 * explanation is already placed in a context where those are inert. Escaping
 * more than necessary makes the output harder to read for no security gain.
 */
function neutraliseProse(text: string): string {
  return text
    // Backticks would open a code span and could swallow surrounding structure.
    .replace(/`/g, "\\`")
    // Asterisks and underscores would open emphasis.
    .replace(/([*_])/g, "\\$1")
    // HTML comments could hide text from a reader but render for a bot, or the
    // reverse. A comment in a diff is a comment in a review too.
    .replace(/<!--/g, "&lt;!--")
    .replace(/-->/g, "--&gt;");
}

/**
 * Render the quoted source.
 *
 * Long quotes are truncated for two reasons: a comment wall is unreadable, and
 * an over-long quote is almost always the model quoting a whole function, which
 * anchors ambiguously and would have been rejected upstream.
 */
export function renderQuote(quote: string): string {
  const truncated = quote.length > MAX_QUOTE_LENGTH;
  const body = truncated ? `${quote.slice(0, MAX_QUOTE_LENGTH)}\n…` : quote;

  const lines = body.split("\n");
  const shown = lines.slice(0, MAX_QUOTE_LINES);
  const elided = lines.length - shown.length;
  const text = elided > 0 ? `${shown.join("\n")}\n… ${elided} more line(s)` : shown.join("\n");

  // The fence is chosen from the final text, so content cannot close it.
  const fence = safeFence(text);
  return `${fence}\n${text}\n${fence}`;
}

/**
 * Render the optional suggestion.
 *
 * The fence is exactly ` ```suggestion ` because that is the syntax GitHub
 * requires — it cannot be grown the way a display fence can. A suggestion
 * containing a backtick run would therefore terminate the block early, so
 * `pipeline/validate.ts` rejects such a suggestion before it ever reaches here.
 * This is the one place in the renderer that cannot defend itself, which is why
 * the check lives upstream.
 */
function renderSuggestion(suggestedCode: string): string {
  return `\`\`\`suggestion\n${suggestedCode}\n\`\`\``;
}

/**
 * The body of a single inline review comment.
 */
export function renderComment(finding: AnchoredFinding): string {
  const parts: string[] = [];

  parts.push(`**${SEVERITY_LABELS[finding.severity]}** — generated by FreeReview.`, "");
  parts.push(neutraliseProse(finding.explanation.trim()), "");
  parts.push(renderQuote(finding.anchoredText));

  if (finding.suggestedCode !== null) {
    parts.push("", renderSuggestion(finding.suggestedCode));
  }

  return parts.join("\n");
}

export interface SummaryInput {
  readonly findings: readonly AnchoredFinding[];
  /** Findings that resolved to no single location, rendered without a line. */
  readonly unanchored: readonly { path: string; explanation: string; severity: Severity }[];
  readonly rejections: readonly { path: string; detail: string; severity: Severity }[];
  readonly modelUsed: string;
  readonly requestsUsed: number;
  readonly filesReviewed: number;
  readonly filesInPr: number;
  readonly privacyMode: "strict" | "relaxed";
  readonly promptVersion: string;
  /**
   * Chunks that were actually sent to a model and returned a usable response.
   *
   * This exists to prevent the single most damaging thing this action could
   * say. Without it, a run where every chunk failed to route renders as
   * "reviewed 1 file and found nothing material" — a clean bill of health for
   * code that was never examined. That is worse than publishing nothing,
   * because it is indistinguishable from a real clean review.
   */
  readonly chunksReviewed: number;
  /** Chunks the run intended to review, before failures. */
  readonly chunksPlanned: number;
  /** Why no chunk could be reviewed, when none could. */
  readonly failureDetail: string | null;
}

/**
 * The top-level review body.
 *
 * The count of unanchored and rejected findings is stated explicitly. A summary
 * that quietly shows only what succeeded reads as "this is everything", which
 * is the specific misunderstanding that makes a partial review look like a
 * clean bill of health.
 */
export function renderSummary(input: SummaryInput): string {
  const lines: string[] = [];

  const critical = input.findings.filter((f) => f.severity === "critical").length;
  const warning = input.findings.filter((f) => f.severity === "warning").length;
  const info = input.findings.filter((f) => f.severity === "info").length;

  lines.push("## FreeReview", "");

  // The no-review case comes first and is never phrased as a result. "Found
  // nothing material" and "could not look at anything" are opposites, and a
  // reader who cannot tell them apart will treat a routing failure as a clean
  // review.
  if (input.chunksReviewed === 0 && input.chunksPlanned > 0) {
    lines.push(
      `**No review was produced.** ${input.chunksPlanned} chunk(s) were prepared but none could be ` +
        "sent to a model successfully, so no code was examined.",
    );
    if (input.failureDetail !== null) {
      lines.push("", `Reason: ${neutraliseProse(input.failureDetail)}`);
    }
    lines.push(
      "",
      "<sub>Treat this as **not reviewed**. It is not a finding of no issues — nothing was looked at.</sub>",
    );
  } else if (input.findings.length === 0 && input.unanchored.length === 0) {
    lines.push(
      `Reviewed ${input.filesReviewed} file(s) and found nothing material. That is a result, not a guarantee — the review covers the changed lines only, and free models miss real defects.`,
    );
  } else {
    const parts: string[] = [];
    if (critical > 0) parts.push(`**${critical} critical**`);
    if (warning > 0) parts.push(`${warning} warning`);
    if (info > 0) parts.push(`${info} note`);
    lines.push(`Found ${parts.join(", ")} across ${input.filesReviewed} file(s).`);
  }

  lines.push("");

  // The advisory framing. Not a disclaimer bolted on — a reader who does not
  // know this is model-generated will read it as a human's judgement.
  lines.push(
    "<sub>Advisory only. Generated by a free-tier language model, which can be wrong. " +
      "This review does not block merging and nothing here was checked by a human. " +
      `Model: \`${input.modelUsed || "none"}\` · ${input.requestsUsed} request(s) · ` +
      `prompt \`${input.promptVersion}\`.</sub>`,
  );

  if (input.privacyMode === "relaxed") {
    // Loud, unmissable, and inside the review itself — not only in the step
    // summary, which a developer reading a PR may never see.
    lines.push("");
    lines.push(
      "> [!WARNING]",
      "> **This review was produced with `privacy_mode: relaxed`.** The diff was sent " +
        "without zero-data-retention enforcement, so a provider may have retained the code. " +
        "Do not use this mode for confidential source.",
    );
  }

  if (input.unanchored.length > 0) {
    lines.push("", "### Not placed on a line", "");
    lines.push(
      "These findings could not be resolved to exactly one line, so they have no inline comment:",
      "",
    );
    for (const item of input.unanchored) {
      lines.push(
        `- **${SEVERITY_LABELS[item.severity]}** \`${item.path}\` — ${neutraliseProse(item.explanation.trim())}`,
      );
    }
  }

  if (input.rejections.length > 0) {
    lines.push("", "### Discarded", "");
    lines.push(
      `${input.rejections.length} finding(s) were discarded before publication:`,
      "",
    );
    for (const item of input.rejections) {
      lines.push(`- \`${item.path}\` — ${neutraliseProse(item.detail.trim())}`);
    }
  }

  if (input.filesReviewed < input.filesInPr) {
    lines.push(
      "",
      `<sub>Reviewed ${input.filesReviewed} of ${input.filesInPr} changed file(s); the rest were ` +
        "filtered as non-reviewable (generated, vendored, lockfiles, or assets).</sub>",
    );
  }

  return lines.join("\n");
}
